theme = "catppuccin_macchiato"

[editor]
scrolloff = 8
mouse = true
middle-click-paste = true
scroll-lines = 3
line-number = "relative"
cursorline = true
cursorcolumn = false
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
completion-trigger-len = 2
completion-replace = false
auto-info = true
true-color = true
rulers = [80, 100]
bufferline = "multiple"
color-modes = true
text-width = 80

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["primary-selection-length", "separator", "position", "spacer", "file-type"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
tabpad = "·"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
max-wrap = 10
wrap-indicator = ""
wrap-at-text-width = true

[keys.insert.j]
k = "normal_mode"
